"""Gold question/SQL set for the eval harness, plus extra labelled questions for the router."""

from dataclasses import dataclass


@dataclass(frozen=True)
class Gold:
    question: str
    sql: str
    difficulty: str  # easy | medium | hard


def _g(q, sql, d):
    return Gold(q, " ".join(sql.split()), d)


GOLD = [
    # ---- easy: single table ----
    _g("How many customers are there?", "SELECT COUNT(*) FROM customers", "easy"),
    _g("List the names of all categories.", "SELECT name FROM categories", "easy"),
    _g("What is the most expensive product?", "SELECT name FROM products ORDER BY price DESC LIMIT 1", "easy"),
    _g("How many products cost more than 100?", "SELECT COUNT(*) FROM products WHERE price > 100", "easy"),
    _g("How many orders are cancelled?", "SELECT COUNT(*) FROM orders WHERE status = 'cancelled'", "easy"),
    _g("Which customers are from Germany?", "SELECT name FROM customers WHERE country = 'Germany'", "easy"),
    _g("What is the average product price?", "SELECT AVG(price) FROM products", "easy"),
    _g("How many distinct countries do customers come from?", "SELECT COUNT(DISTINCT country) FROM customers", "easy"),
    _g("List products that are out of stock.", "SELECT name FROM products WHERE stock = 0", "easy"),
    _g("What is the earliest order date?", "SELECT MIN(order_date) FROM orders", "easy"),
    _g("How many reviews gave a rating of 5?", "SELECT COUNT(*) FROM reviews WHERE rating = 5", "easy"),
    _g("What is the total quantity of items ever ordered?", "SELECT SUM(quantity) FROM order_items", "easy"),
    _g("Show the 5 cheapest products with their prices.", "SELECT name, price FROM products ORDER BY price ASC LIMIT 5", "easy"),
    _g("How many customers signed up in 2023?", "SELECT COUNT(*) FROM customers WHERE signup_date LIKE '2023%'", "easy"),
    _g("What is the average rating across all reviews?", "SELECT AVG(rating) FROM reviews", "easy"),
    _g("How many orders were placed in January 2024?",
       "SELECT COUNT(*) FROM orders WHERE order_date BETWEEN '2024-01-01' AND '2024-01-31'", "easy"),
    _g("How many orders are pending or shipped?", "SELECT COUNT(*) FROM orders WHERE status IN ('pending', 'shipped')", "easy"),
    _g("What is the email of the customer named Alice Novak?", "SELECT email FROM customers WHERE name = 'Alice Novak'", "easy"),
    # ---- medium: one join or aggregation ----
    _g("How many orders has each customer placed? Show customer name and order count.",
       "SELECT c.name, COUNT(o.id) FROM customers c JOIN orders o ON o.customer_id = c.id GROUP BY c.id", "medium"),
    _g("What is the total revenue from delivered orders?",
       "SELECT SUM(oi.quantity * oi.unit_price) FROM order_items oi JOIN orders o ON oi.order_id = o.id WHERE o.status = 'delivered'", "medium"),
    _g("How many products are in each category?",
       "SELECT c.name, COUNT(p.id) FROM categories c JOIN products p ON p.category_id = c.id GROUP BY c.id", "medium"),
    _g("Which product has the most reviews?",
       "SELECT p.name FROM products p JOIN reviews r ON r.product_id = p.id GROUP BY p.id ORDER BY COUNT(*) DESC LIMIT 1", "medium"),
    _g("What is the average price of products in each category?",
       "SELECT c.name, AVG(p.price) FROM categories c JOIN products p ON p.category_id = c.id GROUP BY c.id", "medium"),
    _g("How many orders are there per status?", "SELECT status, COUNT(*) FROM orders GROUP BY status", "medium"),
    _g("What is the average rating of each product? Show product name and average rating.",
       "SELECT p.name, AVG(r.rating) FROM products p JOIN reviews r ON r.product_id = p.id GROUP BY p.id", "medium"),
    _g("List the names of customers who have never placed an order.",
       "SELECT name FROM customers WHERE id NOT IN (SELECT customer_id FROM orders)", "medium"),
    _g("Which country has the most customers?",
       "SELECT country FROM customers GROUP BY country ORDER BY COUNT(*) DESC LIMIT 1", "medium"),
    _g("How many orders did the customer named Bruno Novak place?",
       "SELECT COUNT(*) FROM orders o JOIN customers c ON o.customer_id = c.id WHERE c.name = 'Bruno Novak'", "medium"),
    _g("What is the total value of order 1?", "SELECT SUM(quantity * unit_price) FROM order_items WHERE order_id = 1", "medium"),
    _g("Which products have never been reviewed?",
       "SELECT name FROM products WHERE id NOT IN (SELECT product_id FROM reviews)", "medium"),
    _g("What is the highest rating given to the Wireless Mouse?",
       "SELECT MAX(r.rating) FROM reviews r JOIN products p ON r.product_id = p.id WHERE p.name = 'Wireless Mouse'", "medium"),
    _g("How many reviews are there for each rating value?", "SELECT rating, COUNT(*) FROM reviews GROUP BY rating", "medium"),
    _g("What is the total revenue per month? Show month as YYYY-MM.",
       "SELECT substr(o.order_date, 1, 7) AS month, SUM(oi.quantity * oi.unit_price) FROM orders o JOIN order_items oi ON oi.order_id = o.id GROUP BY month", "medium"),
    _g("List customers from France who signed up before 2023.",
       "SELECT name FROM customers WHERE country = 'France' AND signup_date < '2023-01-01'", "medium"),
    _g("Which products cost more than the average product price?",
       "SELECT name FROM products WHERE price > (SELECT AVG(price) FROM products)", "medium"),
    _g("How many items in total were in order 5?", "SELECT SUM(quantity) FROM order_items WHERE order_id = 5", "medium"),
    _g("How many customers have written at least one review?", "SELECT COUNT(DISTINCT customer_id) FROM reviews", "medium"),
    # ---- hard: multiple joins, having, subqueries ----
    _g("Who are the top 3 customers by total spend? Show name and total spend.",
       "SELECT c.name, SUM(oi.quantity * oi.unit_price) AS spend FROM customers c JOIN orders o ON o.customer_id = c.id JOIN order_items oi ON oi.order_id = o.id GROUP BY c.id ORDER BY spend DESC LIMIT 3", "hard"),
    _g("Which category generates the most revenue?",
       "SELECT c.name FROM categories c JOIN products p ON p.category_id = c.id JOIN order_items oi ON oi.product_id = p.id GROUP BY c.id ORDER BY SUM(oi.quantity * oi.unit_price) DESC LIMIT 1", "hard"),
    _g("List the distinct names of customers who bought a product from the Electronics category.",
       "SELECT DISTINCT c.name FROM customers c JOIN orders o ON o.customer_id = c.id JOIN order_items oi ON oi.order_id = o.id JOIN products p ON p.id = oi.product_id JOIN categories cat ON cat.id = p.category_id WHERE cat.name = 'Electronics'", "hard"),
    _g("What is the average order value per country?",
       "SELECT c.country, AVG(t.total) FROM (SELECT o.id, o.customer_id, SUM(oi.quantity * oi.unit_price) AS total FROM orders o JOIN order_items oi ON oi.order_id = o.id GROUP BY o.id) t JOIN customers c ON c.id = t.customer_id GROUP BY c.country", "hard"),
    _g("Which products have an average rating above 4 with at least 3 reviews?",
       "SELECT p.name FROM products p JOIN reviews r ON r.product_id = p.id GROUP BY p.id HAVING COUNT(*) >= 3 AND AVG(r.rating) > 4", "hard"),
    _g("Which customers have placed more than 8 orders?",
       "SELECT c.name FROM customers c JOIN orders o ON o.customer_id = c.id GROUP BY c.id HAVING COUNT(*) > 8", "hard"),
    _g("What is the revenue per category for delivered orders only?",
       "SELECT cat.name, SUM(oi.quantity * oi.unit_price) FROM categories cat JOIN products p ON p.category_id = cat.id JOIN order_items oi ON oi.product_id = p.id JOIN orders o ON o.id = oi.order_id WHERE o.status = 'delivered' GROUP BY cat.id", "hard"),
    _g("Which customers reviewed a product they never ordered? Show distinct customer names.",
       "SELECT DISTINCT c.name FROM reviews r JOIN customers c ON c.id = r.customer_id WHERE NOT EXISTS (SELECT 1 FROM orders o JOIN order_items oi ON oi.order_id = o.id WHERE o.customer_id = r.customer_id AND oi.product_id = r.product_id)", "hard"),
    _g("For each country, how many distinct products have its customers purchased?",
       "SELECT c.country, COUNT(DISTINCT oi.product_id) FROM customers c JOIN orders o ON o.customer_id = c.id JOIN order_items oi ON oi.order_id = o.id GROUP BY c.country", "hard"),
    _g("Which product has the highest total quantity sold?",
       "SELECT p.name FROM products p JOIN order_items oi ON oi.product_id = p.id GROUP BY p.id ORDER BY SUM(oi.quantity) DESC LIMIT 1", "hard"),
    _g("Which customers have spent more than 3000 in total?",
       "SELECT c.name FROM customers c JOIN orders o ON o.customer_id = c.id JOIN order_items oi ON oi.order_id = o.id GROUP BY c.id HAVING SUM(oi.quantity * oi.unit_price) > 3000", "hard"),
    _g("Which month (YYYY-MM) had the most orders?",
       "SELECT substr(order_date, 1, 7) AS month FROM orders GROUP BY month ORDER BY COUNT(*) DESC LIMIT 1", "hard"),
    _g("How many customers have both placed an order and written a review?",
       "SELECT COUNT(*) FROM customers c WHERE EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id) AND EXISTS (SELECT 1 FROM reviews r WHERE r.customer_id = c.id)", "hard"),
    _g("What is the average number of items per order?",
       "SELECT AVG(n) FROM (SELECT SUM(quantity) AS n FROM order_items GROUP BY order_id)", "hard"),
    _g("Which products have been ordered but currently have zero stock?",
       "SELECT DISTINCT p.name FROM products p JOIN order_items oi ON oi.product_id = p.id WHERE p.stock = 0", "hard"),
    _g("Which category has the highest average review rating?",
       "SELECT c.name FROM categories c JOIN products p ON p.category_id = c.id JOIN reviews r ON r.product_id = p.id GROUP BY c.id ORDER BY AVG(r.rating) DESC LIMIT 1", "hard"),
    _g("For each customer with at least one cancelled order, how many cancelled orders do they have?",
       "SELECT c.name, COUNT(*) FROM customers c JOIN orders o ON o.customer_id = c.id WHERE o.status = 'cancelled' GROUP BY c.id", "hard"),
]

# Labelled questions used only to train the difficulty router (no gold SQL needed).
ROUTER_EXTRA = [
    ("How many products are there?", "easy"), ("List all customer emails.", "easy"),
    ("What is the cheapest product?", "easy"), ("How many orders were delivered?", "easy"),
    ("Show all products in stock.", "easy"), ("What is the latest signup date?", "easy"),
    ("How many reviews have rating 1?", "easy"), ("List customers from Japan.", "easy"),
    ("What is the maximum product price?", "easy"), ("How many orders were placed in 2023?", "easy"),
    ("Show the 10 most expensive products.", "easy"), ("How many customers are from India?", "easy"),
    ("What is the lowest rating in reviews?", "easy"), ("List all order statuses.", "easy"),
    ("How many products have stock below 20?", "easy"), ("Which products cost less than 20?", "easy"),
    ("What is the total stock across all products?", "easy"), ("Count the reviews written in 2024.", "easy"),
    ("How many products does each category have?", "medium"), ("Which customer wrote the most reviews?", "medium"),
    ("What is the total revenue from all orders?", "medium"), ("How many orders did each customer place in 2024?", "medium"),
    ("What is the average rating per product?", "medium"), ("Which products have no orders?", "medium"),
    ("How many reviews does each product have?", "medium"), ("What is the number of orders per month?", "medium"),
    ("List customers who have placed at least one order.", "medium"), ("Which country has the fewest customers?", "medium"),
    ("What is the total value of each order?", "medium"), ("How many orders did Dana Tanaka place?", "medium"),
    ("Which products are more expensive than the Chef Knife?", "medium"), ("What is the average stock per category?", "medium"),
    ("Which product was reviewed most recently?", "medium"), ("How many customers signed up per year?", "medium"),
    ("Which customer placed the most recent order?", "medium"), ("List products in the Books category.", "medium"),
    ("Who are the top 5 customers by number of orders?", "hard"), ("Which category has the highest revenue in 2024?", "hard"),
    ("List customers who bought every product in the Sports category.", "hard"),
    ("Which products have an average rating below 3 and at least 2 reviews?", "hard"),
    ("What is the average spend per customer per country?", "hard"),
    ("Which customers ordered the same product more than once?", "hard"),
    ("For each category, which product has the highest revenue?", "hard"),
    ("Which customers have never reviewed a product they bought?", "hard"),
    ("What percentage of orders are cancelled per country?", "hard"),
    ("Which products were ordered by customers from at least 3 different countries?", "hard"),
    ("What is the month-over-month change in revenue?", "hard"),
    ("Which customers spent more than the average customer spend?", "hard"),
    ("Find the category whose products have the most total stock but the fewest orders.", "hard"),
    ("Which delivered orders contained an out-of-stock product?", "hard"),
    ("How many customers reviewed a product from every category?", "hard"),
    ("Rank countries by average review rating of products their customers bought.", "hard"),
]
